// <auto-generated />
using FirstProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstProject.Migrations
{
    [DbContext(typeof(FirstProjectContext))]
    [Migration("20220819100437_setSeedForCategory")]
    partial class setSeedForCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FirstProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descreption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descreption = "تکنولوژی",
                            Name = "تکنولوژی"
                        },
                        new
                        {
                            Id = 2,
                            Descreption = "پوشاک",
                            Name = "پوشاک"
                        },
                        new
                        {
                            Id = 3,
                            Descreption = "لوازم جانبی خودرو",
                            Name = "لوازم جانبی خودرو"
                        },
                        new
                        {
                            Id = 4,
                            Descreption = "مواد غذایی",
                            Name = "مواد غذایی"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
